version: "3.8"

services:
  mysql:
    build:
      context: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80" # Expose phpMyAdmin on port 8081
    environment:
      PMA_HOST: mysql # This should match the name of the MySQL service
      PMA_USER: symfony_user # Use the same username as MYSQL_USER
      PMA_PASSWORD: symfony_password # Use the same password as MYSQL_PASSWORD
    depends_on:
      - mysql

  php:
    build:
      context: . # Change this to point to the root directory
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/symfony
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # Maps host port 8080 to container port 80
    volumes:
      - ./src:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  python:
    image: python:3.9
    volumes:
      - ./app:/app # Mount the local "app" directory into the container's /app directory
    working_dir: /app # Set the working directory in the container
    command: python script.py # Run your Python script
    depends_on:
      - mysql
